### ISSUE TITLE
磁盘获取的数据，只有第一个磁盘的数据

### ISSUE THREAD

**Issue by awake006** [mzky/easyNmon#1]

**Comment by awake006** [comment]
`T0078,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,49850.7,49850.7,0.0
T0079,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,57811.9,57811.9,0.0
T0080,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,58978.2,58978.2,0.0
T0081,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8766.6,8766.6,0.0
T0082,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,402.7,402.7,0.0
T0083,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,769.1,769.1,0.0
T0084,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1020.2,1020.2,0.0
T0085,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,765.3,765.3,0.0
T0086,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4084.7,4084.7,0.0
T0087,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,272.0,272.0,0.0
T0088,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,514.0,514.0,0.0
T0089,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2805.4,2805.4,0.0
T0090,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,195.2,195.2,0.0
T0091,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1024.1,1024.1,0.0
T0092,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,255.1,255.1,0.0`
`	
DiskWrites=`echo $LINE |awk -F',' '{print "-"$2}'`
`
只获取了第一个磁盘的使用情况

**Comment by mzky** [comment]
### 以下是我复制粘贴的，您也可以搜索下其它解释互相讨论；像cpu和net都有明确的数量信息，可以方便汇总，但是disk确实没有看到
---------------
nmon（包括iostat）对系统I/O的指标截取大部分来自/proc/diskstats，而这些值来自block layer层，LVM里的Logical Volume会“visible as a standard block device”，因此真实的磁盘，LVM的逻辑卷，分区等在这里都会显示，在nmon计算总值时会被重复统计。
Disk Read/Write KB是同一采集时间点下Sheet DISKREAD、DISKWRITE里该行（所有磁盘和分区）数值之和，必然包括了重复值，例如某一时刻sda磁盘共write 1000 KB，其中sda1分区write 700 KB，sda3分区write 300 KB，这一时刻Disk Write应是1000 KB，但这里却会重复统计分区数值，导致显示为Disk Write 2000 KB。Disk I/O也存在同样的问题！

**Comment by awake006** [comment]
> 却会重复统计分区数值

nmon统计结果包括磁盘名称，一般统计只需要获取到sda列的值就可以了
`Disk Write KB/s 204,loop0,sda,sda1,sda2,sda5
T0001,0.0,0.0,0.0,0.0,0.0
T0002,0.0,38.4,38.4,0.0,0.0
T0003,0.0,4848.6,4848.6,0.0,0.0
T0004,0.0,1068.9,1068.9,0.0,0.0
T0005,0.0,1709.9,1709.9,0.0,0.0
T0006,0.0,2661.3,2661.3,0.0,0.0
T0007,0.0,2434.4,2434.4,0.0,0.0
T0008,0.0,1421.9,1421.9,0.0,0.0
T0009,0.0,1279.1,1279.1,0.0,0.0
T0010,0.0,1279.8,1279.8,0.0,0.0
T0011,0.0,1466.7,1466.7,0.0,0.0
T0012,0.0,1201.6,1201.6,0.0,0.0`
比如这份数据，需要获取的是sda列的值，目前您代码中获取的是loop0的值

**Comment by mzky** [comment]
![image](https://user-images.githubusercontent.com/13345233/52986195-e31ed000-3431-11e9-8359-ada3b512f11d.png)
![image](https://user-images.githubusercontent.com/13345233/52986230-05185280-3432-11e9-9f3c-5757e2bc4e50.png)
我这边两台服务器是这样的 取第一列没有问题

另外您提供的数据loop0和sda的值完全相同，不影响结果

**Comment by awake006** [comment]
> ![image](https://user-images.githubusercontent.com/13345233/52986195-e31ed000-3431-11e9-8359-ada3b512f11d.png)
> ![image](https://user-images.githubusercontent.com/13345233/52986230-05185280-3432-11e9-9f3c-5757e2bc4e50.png)
> 我这边两台服务器是这样的 取第一列没有问题
> 
> 另外您提供的数据loop0和sda的值完全相同，不影响结果

有问题的，loop0的值是0，根据列名来获取值，不要根据列号获取值效果会更好

**Comment by mzky** [comment]
我试了很多机器 都没有loop0选项 请提供下系统版本和服务器信息 或者nmon监控数据
