### ISSUE TITLE
net write数据存在bug

### ISSUE THREAD

**Issue by awake006** [mzky/easyNmon#2]
假如服务器目前有两个网卡，那么NET,文件会有5列数据
Network I/O 204,lo-read-KB/s,enp0s31f6-read-KB/s,lo-write-KB/s,enp0s31f6-write-KB/s
T0001,0.0,1.2,0.0,1.0
T0002,0.6,5.7,0.6,5.2
T0003,0.6,218.3,0.6,235.4
T0004,0.6,482.1,0.6,854.8
T0005,0.6,677.2,0.6,865.0
T0006,0.6,629.1,0.6,801.8
T0007,0.6,600.5,0.6,792.1
T0008,0.6,588.1,0.6,788.8
T0009,0.6,631.2,0.6,799.4
T0010,0.8,614.2,0.8,783.7
T0011,0.6,624.8,0.6,732.6
T0012,0.6,724.1,0.6,524.9
#net取write列
`cat NET,|awk -F',' 'BEGIN{c='$c';n='$n'}{for(i=c;i<n;i++)printf "-"$i",";print $i}' >write`
其中n=5,c=3，那么write文件的数据将会是NET，文件的第3,4,5列，共3列数据
-enp0s31f6-read-KB/s,-lo-write-KB/s,enp0s31f6-write-KB/s
-1.2,-0.0,1.0
-5.7,-0.6,5.2
-218.3,-0.6,235.4
-482.1,-0.6,854.8
-677.2,-0.6,865.0
-629.1,-0.6,801.8
-600.5,-0.6,792.1
-588.1,-0.6,788.8
-631.2,-0.6,799.4
-614.2,-0.8,783.7
-624.8,-0.6,732.6
-724.1,-0.6,524.9
而正确的write文件的数据应该是NET,文件的第4,5列数据，尝试修改为
`cat NET,|awk -F',' 'BEGIN{c='$c';n='$n'}{for(i=c+1;i<n;i++)printf "-"$i",";print "-"$i}' >write`
lo-write-KB/s,enp0s31f6-write-KB/s
-0.0,-1.0
-0.6,-5.2
-0.6,-235.4
-0.6,-854.8
-0.6,-865.0
-0.6,-801.8
-0.6,-792.1
-0.6,-788.8
-0.6,-799.4
-0.8,-783.7
-0.6,-732.6
-0.6,-524.9

**Comment by mzky** [comment]
感谢关注！不过要是按照你的改法，我这边所有的服务器监控结果就都是错误的了
![image](https://user-images.githubusercontent.com/13345233/52986567-ef575d00-3432-11e9-899e-97f5eee30076.png)
![image](https://user-images.githubusercontent.com/13345233/52987219-3ba39c80-3435-11e9-94e9-bef1e40b9c1f.png)
![image](https://user-images.githubusercontent.com/13345233/52987282-6db4fe80-3435-11e9-8d48-263518a4e320.png)

可以把你那边的nmon数据文件邮件发给我看下

**Comment by mzky** [comment]
反复验了一下 只留1个网卡确实会有问题 已修改
