### ISSUE TITLE
cpu占用超80%看不到

### ISSUE THREAD

**Issue by wangbinaaa** [mzky/easyNmon#4]
cpu统计表上限为80，超过80%的值看不到，使用1.7版本出现此现象
![image](https://user-images.githubusercontent.com/44644692/62408290-3dcf7100-b5f9-11e9-809d-5ccb9a317176.png)

**Comment by mzky** [comment]
感谢反馈，但是我这没有出现过这种问题，建议用`time echo "scale=50000; 4*a(1)" | bc -l -q`，压一下cpu试试，单条命令可以呀满一个核心cpu，如果是多核心需要多执行几条此命令
![image](https://user-images.githubusercontent.com/13345233/62431379-b9483400-b759-11e9-828c-2aaaf6104f1c.png)

**Comment by wangbinaaa** [comment]
现象看起来像是，比例尺缩放以user%为基准，而不是以sys%为基准。
我的环境正在进行测试，暂时不能额外对造成压力来验证你说的方法。
谢谢你的回复

**Comment by mzky** [comment]
确实是基准问题，已修正

**Comment by wangbinaaa** [comment]
谢谢你的帮助 mzky
